apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5-operator-catalog
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: p5-operator-catalog
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
