apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtx-schema-management
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: dtx-schema-management
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
