apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5-dag-compiler
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: p5-dag-compiler
          resources:
            requests:
              memory: "2048Mi"
              cpu: "500m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
