apiVersion: v1
kind: Service
metadata:
  name: p5-dag-compiler
  labels:
    app: p5-dag-compiler
spec:
  type: ClusterIP
  selector:
    app: p5-dag-compiler
  ports:
    - port: 50002
      targetPort: 50002
      protocol: TCP
      name: http
