apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5-operator-catalog
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: p5-operator-catalog
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
