apiVersion: v1
kind: Service
metadata:
  name: p5-operator-catalog
  labels:
    app: p5-operator-catalog
spec:
  type: ClusterIP
  selector:
    app: p5-operator-catalog
  ports:
    - port: 50001
      targetPort: 50001
      protocol: TCP
      name: http
