apiVersion: v1
kind: Service
metadata:
  name: dtx-portal
  labels:
    app: dtx-portal
spec:
  type: ClusterIP
  selector:
    app: dtx-portal
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http